config/routes.rb
Jninja::Application.routes.draw do

  get "jquery/index"

  get "tweets/admin"

  resources :tweets

  root :to => "jquery#index", :as => "jquery"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jquery_controller.rb
class JqueryController < ApplicationController
  def index
    @hello = "Welcome to jQuery world!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.xml
  def index

  end
  
  # GET /tweets/admin
  # GET /tweets/admin.xml
  def admin
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tweets }
    end
  end
  
  # GET /tweets/1
  # GET /tweets/1.xml
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.xml
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.xml
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to(@tweet, :notice => 'Tweet was successfully created.') }
        format.xml  { render :xml => @tweet, :status => :created, :location => @tweet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.xml
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to(@tweet, :notice => 'Tweet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.xml
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to(tweets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jquery_helper.rb
module JqueryHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/jquery/index.html.erb
<h2>Page content</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= render "shared/gallery" %>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

<%= render "shared/rollover" %>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= render "shared/timer" %>

<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= render "shared/slideshow" %>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

<%= render "shared/news" %>

<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= render "shared/scroller" %>

<%= javascript_tag do %>
  flashMessage('<%= @hello %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jninja</title>
  <%= stylesheet_link_tag "jquery-ui", "fancybox", "application" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "fancybox", "easing", "mousewheel", "innerfade", "scrollto" %>
  <%= csrf_meta_tag %>
</head>
<body>

<!-- set message to fire in views using flashMessage() script -->
<div id="flash"></div>

<div id="wrap">

  <div id="bookmark"><div id="seam"><div>W</div></div></div>

  <div id="sidebar">
    <ul id="sidenav" class="nav vertical">
      <li><a href="#top">Back to top</a></li>
    </ul>
  </div>

  <div id="page">
  
    <%= yield %>

  </div>
  
  <div style="clear:both;"></div>
  
</div>

</body>
</html>

app/views/shared/_accordion.html.erb
<div id="bio">
  <h2>Who's Hot Right Now?</h2>
  
  <h3>Beau Dandy</h3>
  <div>
    <div class="media"><img src="/images/beau_100.jpg" width="100px" height="100px" alt="Beau Dandy" /></div>
    <p class="content">Content about Beau Dandy</p>
    <div style="clear:both;"></div>
  </div>
  
  <h3>Johnny Stardust</h3>
  <div>
    <div class="media"><img src="/images/johnny_100.jpg" width="100px" height="100px" alt="Johnny Stardust" /></div>
    <p class="content">Content about Johnny Stardust</p>
    <div style="clear:both;"></div>
  </div>
  
  <h3>Glendatronix</h3>
  <div>
    <div class="media"><img src="/images/glenda_100.jpg" width="100px" height="100px" alt="Glendatronix" /></div>
    <p class="content">Content about Glendatronix</p>
    <div style="clear:both;"></div>
  </div>

  <h3>Kellie</h3>
  <div>
    <div class="media"><a href="/images/kellie_400.jpg" class="lightbox"><img src="images/kellie_100.jpg" width="100px" height="100px" alt="Kellie" /></a></div>
    <p class="content">Content about Kellie</p>
    <div style="clear:both;"></div>
  </div>
</div>

app/views/shared/_gallery.html.erb
<div id="gallery">

  <h3>Fancybox photo gallery</h3>

  <div class="media">
    <a href="/images/beau_400.jpg" rel="celeb">
      <img src="/images/beau_100.jpg" alt="Beau Dandy" />
    </a>
  </div>

  <div class="media">
    <a href="/images/johnny_400.jpg" rel="celeb">
      <img src="/images/johnny_100.jpg" alt="Johnny Stardust" />
    </a>
  </div>

  <div class="media">
    <a href="/images/glenda_400.jpg" rel="celeb">
      <img src="/images/glenda_100.jpg" alt="Glendatronix" />
    </a>
  </div>

  <div class="media">
    <a href="/images/kellie_400.jpg" rel="celeb">
      <img src="/images/kellie_100.jpg" alt="Kellie" />
    </a>
  </div>
  
  <div style="clear:both;"></div>

</div>

app/views/shared/_menu.html.erb
<ul id="menu">
  <li><a href="#">What's new?</a>
    <ul class="active">
      <li><a href="#">Weekly specials</a></li>
      <li><a href="#">Last night's pics!</a></li>
      <li><a href="#">Users' comments</a></li>
    </ul>
  </li>
  <li><a href="#">Member extras</a>
    <ul>
      <li><a href="#">Premium celebrities</a></li>
      <li><a href="#">24-hour surveillance</a></li>
    </ul>
  </li>
</ul>

app/views/shared/_news.html.erb
<div id="news">
  <h3>News</h3>
  <ul>
    <li><a href="#">Baron Von Jovi spotted ...</a></li>
    <li><a href="#">Mo' Fat signs up-and-coming rapper ...</a></li>
    <li><a href="#">Glentronix rumored to be ...</a></li>
    <li><a href="#">Man claims to be Darth Fader's son ...</a></li>
  </ul>
</div>

app/views/shared/_rollover.html.erb
<div id="fader">
  <h3>Rollover fader</h3>
  <img src="/images/glenda_200.jpg" width="200px" height="200px" alt="Glendatronix" />
  <img class="to" src="/images/fader_200.jpg" width="200px" height="200px" alt="Darth Fader" />
</div>

app/views/shared/_scroller.html.erb
<div id="scroller">
  <div id="scroller_inner">
    <img src="/images/glenda_100.jpg" alt="Glendatronix" />
    <img src="/images/fader_100.jpg" alt="Darth Fader" />
    <img src="/images/beau_100.jpg" alt="Beau Dandy" />
    <img src="/images/johnny_100.jpg" alt="John Stardust" />
    <img src="/images/mofat_100.jpg" alt="Mo' Fat" />
    <img src="/images/glenda_100.jpg" alt="Glendatronix" />
    <img src="/images/fader_100.jpg" alt="Darth Fader" />
    <img src="/images/beau_100.jpg" alt="Beau Dandy" />
    <img src="/images/johnny_100.jpg" alt="John Stardust" />
    <img src="/images/mofat_100.jpg" alt="Mo' Fat" />
    <img src="/images/glenda_100.jpg" alt="Glendatronix" />
    <img src="/images/fader_100.jpg" alt="Darth Fader" />
    <img src="/images/beau_100.jpg" alt="Beau Dandy" />
    <img src="/images/johnny_100.jpg" alt="John Stardust" />
    <img src="/images/mofat_100.jpg" alt="Mo' Fat" />
  </div>
</div>

app/views/shared/_slideshow.html.erb
<div id="slideshow">
  <h3>Photo slideshow</h3>
  <img src="/images/glenda_200.jpg" alt="Glendatronix" />
  <img src="/images/fader_200.jpg" alt="Darth Fader" />
  <img src="/images/beau_200.jpg" alt="Beau Dandy" />
  <img src="/images/johnny_200.jpg" alt="John Stardust" />
  <img src="/images/mofat_200.jpg" alt="Mo' Fat" />
</div>

app/views/shared/_timer.html.erb
<div id="timer">
  <h3>Javascript timers</h3>
  <div id="green" class="box">Go!</div>
  <div id="red" class="box">Go!</div>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :tweeted_by %><br />
    <%= f.text_field :tweeted_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/admin.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Tweeted by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.message %></td>
    <td><%= tweet.tweeted_by %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<script type="text/javascript">
  flashMessage('<%= notice %>');
</script>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Tweeted by:</b>
  <%= @tweet.tweeted_by %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>